{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "752b4f18",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "1e5c58ad",
   "metadata": {},
   "outputs": [],
   "source": [
    "pd.set_option('display.max_colwidth', None)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "f94f5f2d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>site</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>https://microstrategy-mex.privalia-test.com.mx/MicroStrategy/servlet/mstrWeb</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>https://microstrategy-mex.privalia-test.com.mx/MicroStrategy/servlet/mstrWeb</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>https://rundeck-bi.privalia-test.com.mx</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                                           site\n",
       "0  https://microstrategy-mex.privalia-test.com.mx/MicroStrategy/servlet/mstrWeb\n",
       "1  https://microstrategy-mex.privalia-test.com.mx/MicroStrategy/servlet/mstrWeb\n",
       "2                                       https://rundeck-bi.privalia-test.com.mx"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "colnames=['site'] \n",
    "file = 'urls.txt'\n",
    "URLS = pd.read_csv(file, names=colnames, header=None)\n",
    "URLS.head(3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "d8b9c317",
   "metadata": {},
   "outputs": [],
   "source": [
    "headers = {\n",
    "    'User-Agent': 'Python_connection',\n",
    "    'From': 'some_id' \n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "d3807803",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_200 (url):\n",
    "    try:\n",
    "        response = requests.get(url,headers=headers)\n",
    "        return response.status_code\n",
    "    except requests.exceptions.ConnectionError as ConnectionError:\n",
    "        return ConnectionError\n",
    "    except requests.exceptions.HTTPError as HTTPError:\n",
    "        return HTTPError\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d9a2f80f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def to_txt (url):\n",
    "    string = str(url)\n",
    "    return string"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "52424d96",
   "metadata": {},
   "outputs": [],
   "source": [
    "URLS['response']=URLS.apply(lambda x: get_200(x['site']) ,axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "e73de04d",
   "metadata": {},
   "outputs": [],
   "source": [
    "URLS['Response_service']=URLS.apply(lambda x: to_txt(x['response']) ,axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "0d34691e",
   "metadata": {},
   "outputs": [],
   "source": [
    "URLS['Response_service_data'] = [x[:19] for x in URLS['Response_service']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "910a5cc7",
   "metadata": {},
   "outputs": [],
   "source": [
    "response = URLS.pivot_table(index=['Response_service_data'], aggfunc='size')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "337cca43",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Response_service_data\n",
       "403                     3\n",
       "HTTPSConnectionPool    51\n",
       "dtype: int64"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "6b2a6e8e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>site</th>\n",
       "      <th>response</th>\n",
       "      <th>Response_service</th>\n",
       "      <th>Response_service_data</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>https://microstrategy-mex.privalia-test.com.mx/MicroStrategy/servlet/mstrWeb</td>\n",
       "      <td>403</td>\n",
       "      <td>403</td>\n",
       "      <td>403</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>https://microstrategy-mex.privalia-test.com.mx/MicroStrategy/servlet/mstrWeb</td>\n",
       "      <td>403</td>\n",
       "      <td>403</td>\n",
       "      <td>403</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>https://rundeck-bi.privalia-test.com.mx</td>\n",
       "      <td>403</td>\n",
       "      <td>403</td>\n",
       "      <td>403</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>https://sacarino-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='sacarino-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd80eb0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='sacarino-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd80eb0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>https://sugarcrmdb-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='sugarcrmdb-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd9f3a0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='sugarcrmdb-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd9f3a0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>https://vertica01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='vertica01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd9ff10&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='vertica01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd9ff10&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>https://kettledb-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='kettledb-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd1e6d0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='kettledb-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd1e6d0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>https://finance-api-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='finance-api-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd1efa0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='finance-api-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd1efa0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>https://finance-api01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='finance-api01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd27220&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='finance-api01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd27220&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>https://tpv-api01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='tpv-api01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd27af0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='tpv-api01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd27af0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>https://finance-api02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='finance-api02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd34400&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='finance-api02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd34400&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>https://tpv-api02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='tpv-api02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd34cd0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='tpv-api02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd34cd0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>https://backoffice-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='backoffice-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcbe5e0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='backoffice-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcbe5e0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>https://backoffice01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='backoffice01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcbeeb0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='backoffice01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcbeeb0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>https://backoffice02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='backoffice02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcca7c0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='backoffice02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcca7c0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>https://bnr.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='bnr.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcd10d0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='bnr.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcd10d0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>https://boloc-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='boloc-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcd19a0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='boloc-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcd19a0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>https://catalogapi-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='catalogapi-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcdb2b0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='catalogapi-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcdb2b0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>https://maf-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='maf-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcdbb80&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='maf-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcdbb80&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>https://maf01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='maf01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dce6490&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='maf01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dce6490&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>https://maf02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='maf02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dce6d60&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='maf02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dce6d60&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>https://apiproductionactivity-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='apiproductionactivity-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcef670&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='apiproductionactivity-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcef670&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>https://apiproductionactivity01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='apiproductionactivity01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dceff40&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='apiproductionactivity01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dceff40&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>https://apiproductionactivity02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='apiproductionactivity02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcfa850&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='apiproductionactivity02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcfa850&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>https://rundeck-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='rundeck-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc83160&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='rundeck-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc83160&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>https://sender.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='sender.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc83a30&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='sender.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc83a30&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>https://sku-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='sku-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc8d340&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='sku-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc8d340&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>https://sku01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='sku01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc8dc10&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='sku01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc8dc10&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>https://sku02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='sku02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc97520&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='sku02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc97520&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>https://sugarcrm-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='sugarcrm-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc97df0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='sugarcrm-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc97df0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>https://suppliersportal-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='suppliersportal-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dca1700&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='suppliersportal-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dca1700&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>https://suppliersportal01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='suppliersportal01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dca1fd0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='suppliersportal01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dca1fd0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>https://suppliersportal02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='suppliersportal02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcac8e0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='suppliersportal02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcac8e0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>https://apitms-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='apitms-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcb41f0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='apitms-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcb41f0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>https://apitms01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='apitms01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcb4ac0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='apitms01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcb4ac0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>https://apitms02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='apitms02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc3d3d0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='apitms02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc3d3d0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>https://productionactivity-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='productionactivity-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc3dca0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='productionactivity-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc3dca0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>https://productionactivity01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='productionactivity01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc495b0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='productionactivity01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc495b0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>https://productionactivity02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='productionactivity02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc49e80&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='productionactivity02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc49e80&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>https://apiwarehouse01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='apiwarehouse01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc51790&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='apiwarehouse01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc51790&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>https://apiwarehouse-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='apiwarehouse-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc5e0a0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='apiwarehouse-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc5e0a0&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>https://apiwarehouse02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='apiwarehouse02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc5e970&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='apiwarehouse02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc5e970&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>https://auth-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='auth-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc66280&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='auth-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc66280&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>https://auth01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='auth01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc66b50&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='auth01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc66b50&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>https://auth02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='auth02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc6f460&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='auth02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc6f460&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>https://tpv-api01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='tpv-api01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc6fd30&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='tpv-api01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc6fd30&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>https://tpv-api-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='tpv-api-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc7a640&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='tpv-api-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc7a640&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>https://tpv-api02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='tpv-api02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc7af10&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='tpv-api02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc7af10&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>https://apicrm-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='apicrm-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc04820&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='apicrm-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc04820&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>https://apicrm01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='apicrm01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc10130&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='apicrm01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc10130&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50</th>\n",
       "      <td>https://apicrm02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='apicrm02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc10a30&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='apicrm02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc10a30&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>51</th>\n",
       "      <td>https://zparser-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='zparser-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc16340&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='zparser-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc16340&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>52</th>\n",
       "      <td>https://zparser01-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='zparser01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc16c10&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='zparser01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc16c10&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>53</th>\n",
       "      <td>https://zparser02-mex.privalia-test.com.mx</td>\n",
       "      <td>HTTPSConnectionPool(host='zparser02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc22520&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool(host='zparser02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('&lt;urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc22520&gt;: Failed to establish a new connection: [Errno -2] Name or service not known'))</td>\n",
       "      <td>HTTPSConnectionPool</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                                            site  \\\n",
       "0   https://microstrategy-mex.privalia-test.com.mx/MicroStrategy/servlet/mstrWeb   \n",
       "1   https://microstrategy-mex.privalia-test.com.mx/MicroStrategy/servlet/mstrWeb   \n",
       "2                                        https://rundeck-bi.privalia-test.com.mx   \n",
       "3                                      https://sacarino-mex.privalia-test.com.mx   \n",
       "4                                    https://sugarcrmdb-mex.privalia-test.com.mx   \n",
       "5                                     https://vertica01-mex.privalia-test.com.mx   \n",
       "6                                      https://kettledb-mex.privalia-test.com.mx   \n",
       "7                                   https://finance-api-mex.privalia-test.com.mx   \n",
       "8                                 https://finance-api01-mex.privalia-test.com.mx   \n",
       "9                                     https://tpv-api01-mex.privalia-test.com.mx   \n",
       "10                                https://finance-api02-mex.privalia-test.com.mx   \n",
       "11                                    https://tpv-api02-mex.privalia-test.com.mx   \n",
       "12                                   https://backoffice-mex.privalia-test.com.mx   \n",
       "13                                 https://backoffice01-mex.privalia-test.com.mx   \n",
       "14                                 https://backoffice02-mex.privalia-test.com.mx   \n",
       "15                                              https://bnr.privalia-test.com.mx   \n",
       "16                                        https://boloc-mex.privalia-test.com.mx   \n",
       "17                                   https://catalogapi-mex.privalia-test.com.mx   \n",
       "18                                          https://maf-mex.privalia-test.com.mx   \n",
       "19                                        https://maf01-mex.privalia-test.com.mx   \n",
       "20                                        https://maf02-mex.privalia-test.com.mx   \n",
       "21                        https://apiproductionactivity-mex.privalia-test.com.mx   \n",
       "22                      https://apiproductionactivity01-mex.privalia-test.com.mx   \n",
       "23                      https://apiproductionactivity02-mex.privalia-test.com.mx   \n",
       "24                                      https://rundeck-mex.privalia-test.com.mx   \n",
       "25                                           https://sender.privalia-test.com.mx   \n",
       "26                                          https://sku-mex.privalia-test.com.mx   \n",
       "27                                        https://sku01-mex.privalia-test.com.mx   \n",
       "28                                        https://sku02-mex.privalia-test.com.mx   \n",
       "29                                     https://sugarcrm-mex.privalia-test.com.mx   \n",
       "30                              https://suppliersportal-mex.privalia-test.com.mx   \n",
       "31                            https://suppliersportal01-mex.privalia-test.com.mx   \n",
       "32                            https://suppliersportal02-mex.privalia-test.com.mx   \n",
       "33                                       https://apitms-mex.privalia-test.com.mx   \n",
       "34                                     https://apitms01-mex.privalia-test.com.mx   \n",
       "35                                     https://apitms02-mex.privalia-test.com.mx   \n",
       "36                           https://productionactivity-mex.privalia-test.com.mx   \n",
       "37                         https://productionactivity01-mex.privalia-test.com.mx   \n",
       "38                         https://productionactivity02-mex.privalia-test.com.mx   \n",
       "39                               https://apiwarehouse01-mex.privalia-test.com.mx   \n",
       "40                                 https://apiwarehouse-mex.privalia-test.com.mx   \n",
       "41                               https://apiwarehouse02-mex.privalia-test.com.mx   \n",
       "42                                         https://auth-mex.privalia-test.com.mx   \n",
       "43                                       https://auth01-mex.privalia-test.com.mx   \n",
       "44                                       https://auth02-mex.privalia-test.com.mx   \n",
       "45                                    https://tpv-api01-mex.privalia-test.com.mx   \n",
       "46                                      https://tpv-api-mex.privalia-test.com.mx   \n",
       "47                                    https://tpv-api02-mex.privalia-test.com.mx   \n",
       "48                                       https://apicrm-mex.privalia-test.com.mx   \n",
       "49                                     https://apicrm01-mex.privalia-test.com.mx   \n",
       "50                                     https://apicrm02-mex.privalia-test.com.mx   \n",
       "51                                      https://zparser-mex.privalia-test.com.mx   \n",
       "52                                    https://zparser01-mex.privalia-test.com.mx   \n",
       "53                                    https://zparser02-mex.privalia-test.com.mx   \n",
       "\n",
       "                                                                                                                                                                                                                                                                                                        response  \\\n",
       "0                                                                                                                                                                                                                                                                                                            403   \n",
       "1                                                                                                                                                                                                                                                                                                            403   \n",
       "2                                                                                                                                                                                                                                                                                                            403   \n",
       "3                  HTTPSConnectionPool(host='sacarino-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd80eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "4                HTTPSConnectionPool(host='sugarcrmdb-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd9f3a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "5                 HTTPSConnectionPool(host='vertica01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd9ff10>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "6                  HTTPSConnectionPool(host='kettledb-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd1e6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "7               HTTPSConnectionPool(host='finance-api-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd1efa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "8             HTTPSConnectionPool(host='finance-api01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd27220>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "9                 HTTPSConnectionPool(host='tpv-api01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd27af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "10            HTTPSConnectionPool(host='finance-api02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd34400>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "11                HTTPSConnectionPool(host='tpv-api02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd34cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "12               HTTPSConnectionPool(host='backoffice-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcbe5e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "13             HTTPSConnectionPool(host='backoffice01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcbeeb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "14             HTTPSConnectionPool(host='backoffice02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcca7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "15                          HTTPSConnectionPool(host='bnr.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcd10d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "16                    HTTPSConnectionPool(host='boloc-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcd19a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "17               HTTPSConnectionPool(host='catalogapi-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcdb2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "18                      HTTPSConnectionPool(host='maf-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcdbb80>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "19                    HTTPSConnectionPool(host='maf01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dce6490>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "20                    HTTPSConnectionPool(host='maf02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dce6d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "21    HTTPSConnectionPool(host='apiproductionactivity-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcef670>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "22  HTTPSConnectionPool(host='apiproductionactivity01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dceff40>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "23  HTTPSConnectionPool(host='apiproductionactivity02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcfa850>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "24                  HTTPSConnectionPool(host='rundeck-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc83160>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "25                       HTTPSConnectionPool(host='sender.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc83a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "26                      HTTPSConnectionPool(host='sku-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc8d340>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "27                    HTTPSConnectionPool(host='sku01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc8dc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "28                    HTTPSConnectionPool(host='sku02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc97520>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "29                 HTTPSConnectionPool(host='sugarcrm-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc97df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "30          HTTPSConnectionPool(host='suppliersportal-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dca1700>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "31        HTTPSConnectionPool(host='suppliersportal01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dca1fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "32        HTTPSConnectionPool(host='suppliersportal02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcac8e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "33                   HTTPSConnectionPool(host='apitms-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcb41f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "34                 HTTPSConnectionPool(host='apitms01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcb4ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "35                 HTTPSConnectionPool(host='apitms02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc3d3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "36       HTTPSConnectionPool(host='productionactivity-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc3dca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "37     HTTPSConnectionPool(host='productionactivity01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc495b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "38     HTTPSConnectionPool(host='productionactivity02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc49e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "39           HTTPSConnectionPool(host='apiwarehouse01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc51790>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "40             HTTPSConnectionPool(host='apiwarehouse-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc5e0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "41           HTTPSConnectionPool(host='apiwarehouse02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc5e970>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "42                     HTTPSConnectionPool(host='auth-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc66280>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "43                   HTTPSConnectionPool(host='auth01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc66b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "44                   HTTPSConnectionPool(host='auth02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc6f460>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "45                HTTPSConnectionPool(host='tpv-api01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc6fd30>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "46                  HTTPSConnectionPool(host='tpv-api-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc7a640>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "47                HTTPSConnectionPool(host='tpv-api02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc7af10>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "48                   HTTPSConnectionPool(host='apicrm-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc04820>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "49                 HTTPSConnectionPool(host='apicrm01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc10130>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "50                 HTTPSConnectionPool(host='apicrm02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc10a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "51                  HTTPSConnectionPool(host='zparser-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc16340>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "52                HTTPSConnectionPool(host='zparser01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc16c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "53                HTTPSConnectionPool(host='zparser02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc22520>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "\n",
       "                                                                                                                                                                                                                                                                                                Response_service  \\\n",
       "0                                                                                                                                                                                                                                                                                                            403   \n",
       "1                                                                                                                                                                                                                                                                                                            403   \n",
       "2                                                                                                                                                                                                                                                                                                            403   \n",
       "3                  HTTPSConnectionPool(host='sacarino-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd80eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "4                HTTPSConnectionPool(host='sugarcrmdb-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd9f3a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "5                 HTTPSConnectionPool(host='vertica01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd9ff10>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "6                  HTTPSConnectionPool(host='kettledb-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd1e6d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "7               HTTPSConnectionPool(host='finance-api-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd1efa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "8             HTTPSConnectionPool(host='finance-api01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd27220>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "9                 HTTPSConnectionPool(host='tpv-api01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd27af0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "10            HTTPSConnectionPool(host='finance-api02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd34400>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "11                HTTPSConnectionPool(host='tpv-api02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dd34cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "12               HTTPSConnectionPool(host='backoffice-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcbe5e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "13             HTTPSConnectionPool(host='backoffice01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcbeeb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "14             HTTPSConnectionPool(host='backoffice02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcca7c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "15                          HTTPSConnectionPool(host='bnr.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcd10d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "16                    HTTPSConnectionPool(host='boloc-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcd19a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "17               HTTPSConnectionPool(host='catalogapi-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcdb2b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "18                      HTTPSConnectionPool(host='maf-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcdbb80>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "19                    HTTPSConnectionPool(host='maf01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dce6490>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "20                    HTTPSConnectionPool(host='maf02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dce6d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "21    HTTPSConnectionPool(host='apiproductionactivity-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcef670>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "22  HTTPSConnectionPool(host='apiproductionactivity01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dceff40>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "23  HTTPSConnectionPool(host='apiproductionactivity02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcfa850>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "24                  HTTPSConnectionPool(host='rundeck-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc83160>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "25                       HTTPSConnectionPool(host='sender.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc83a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "26                      HTTPSConnectionPool(host='sku-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc8d340>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "27                    HTTPSConnectionPool(host='sku01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc8dc10>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "28                    HTTPSConnectionPool(host='sku02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc97520>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "29                 HTTPSConnectionPool(host='sugarcrm-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc97df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "30          HTTPSConnectionPool(host='suppliersportal-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dca1700>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "31        HTTPSConnectionPool(host='suppliersportal01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dca1fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "32        HTTPSConnectionPool(host='suppliersportal02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcac8e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "33                   HTTPSConnectionPool(host='apitms-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcb41f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "34                 HTTPSConnectionPool(host='apitms01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dcb4ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "35                 HTTPSConnectionPool(host='apitms02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc3d3d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "36       HTTPSConnectionPool(host='productionactivity-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc3dca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "37     HTTPSConnectionPool(host='productionactivity01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc495b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "38     HTTPSConnectionPool(host='productionactivity02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc49e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "39           HTTPSConnectionPool(host='apiwarehouse01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc51790>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "40             HTTPSConnectionPool(host='apiwarehouse-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc5e0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "41           HTTPSConnectionPool(host='apiwarehouse02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc5e970>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "42                     HTTPSConnectionPool(host='auth-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc66280>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "43                   HTTPSConnectionPool(host='auth01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc66b50>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "44                   HTTPSConnectionPool(host='auth02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc6f460>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "45                HTTPSConnectionPool(host='tpv-api01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc6fd30>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "46                  HTTPSConnectionPool(host='tpv-api-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc7a640>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "47                HTTPSConnectionPool(host='tpv-api02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc7af10>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "48                   HTTPSConnectionPool(host='apicrm-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc04820>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "49                 HTTPSConnectionPool(host='apicrm01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc10130>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "50                 HTTPSConnectionPool(host='apicrm02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc10a30>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "51                  HTTPSConnectionPool(host='zparser-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc16340>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "52                HTTPSConnectionPool(host='zparser01-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc16c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "53                HTTPSConnectionPool(host='zparser02-mex.privalia-test.com.mx', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f493dc22520>: Failed to establish a new connection: [Errno -2] Name or service not known'))   \n",
       "\n",
       "   Response_service_data  \n",
       "0                    403  \n",
       "1                    403  \n",
       "2                    403  \n",
       "3    HTTPSConnectionPool  \n",
       "4    HTTPSConnectionPool  \n",
       "5    HTTPSConnectionPool  \n",
       "6    HTTPSConnectionPool  \n",
       "7    HTTPSConnectionPool  \n",
       "8    HTTPSConnectionPool  \n",
       "9    HTTPSConnectionPool  \n",
       "10   HTTPSConnectionPool  \n",
       "11   HTTPSConnectionPool  \n",
       "12   HTTPSConnectionPool  \n",
       "13   HTTPSConnectionPool  \n",
       "14   HTTPSConnectionPool  \n",
       "15   HTTPSConnectionPool  \n",
       "16   HTTPSConnectionPool  \n",
       "17   HTTPSConnectionPool  \n",
       "18   HTTPSConnectionPool  \n",
       "19   HTTPSConnectionPool  \n",
       "20   HTTPSConnectionPool  \n",
       "21   HTTPSConnectionPool  \n",
       "22   HTTPSConnectionPool  \n",
       "23   HTTPSConnectionPool  \n",
       "24   HTTPSConnectionPool  \n",
       "25   HTTPSConnectionPool  \n",
       "26   HTTPSConnectionPool  \n",
       "27   HTTPSConnectionPool  \n",
       "28   HTTPSConnectionPool  \n",
       "29   HTTPSConnectionPool  \n",
       "30   HTTPSConnectionPool  \n",
       "31   HTTPSConnectionPool  \n",
       "32   HTTPSConnectionPool  \n",
       "33   HTTPSConnectionPool  \n",
       "34   HTTPSConnectionPool  \n",
       "35   HTTPSConnectionPool  \n",
       "36   HTTPSConnectionPool  \n",
       "37   HTTPSConnectionPool  \n",
       "38   HTTPSConnectionPool  \n",
       "39   HTTPSConnectionPool  \n",
       "40   HTTPSConnectionPool  \n",
       "41   HTTPSConnectionPool  \n",
       "42   HTTPSConnectionPool  \n",
       "43   HTTPSConnectionPool  \n",
       "44   HTTPSConnectionPool  \n",
       "45   HTTPSConnectionPool  \n",
       "46   HTTPSConnectionPool  \n",
       "47   HTTPSConnectionPool  \n",
       "48   HTTPSConnectionPool  \n",
       "49   HTTPSConnectionPool  \n",
       "50   HTTPSConnectionPool  \n",
       "51   HTTPSConnectionPool  \n",
       "52   HTTPSConnectionPool  \n",
       "53   HTTPSConnectionPool  "
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "URLS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d0a0c7ec",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5eef14f5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b7e534f2",
   "metadata": {},
   "outputs": [],
   "source": [
    "URLS['response_80']=URLS.apply(lambda x: get_200(x['site']+':80') ,axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7df0fabd",
   "metadata": {},
   "outputs": [],
   "source": [
    "URLS['Response_service']=URLS.apply(lambda x: to_txt(x['response_80']) ,axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e23f9e93",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "URLS['Response_service_data_80'] = [x[:19] for x in URLS['response_80']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1b6e351b",
   "metadata": {},
   "outputs": [],
   "source": [
    "response_80 = URLS.pivot_table(index=['response_80'], aggfunc='size')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f138b611",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "57fd2d2a",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b79690b0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6557daf5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "47b8c7e6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
